import homelogo from "../assets/homelogo.png"
import "./Home.css";

const Home = () => {
    return (
        <div className="container">
            <div className="aboutContainer">
                <p>
                Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut sem tortor, faucibus in pharetra in, malesuada in ante. Cras in ultricies mi, sed tempus enim. Duis vel dui luctus, maximus purus non, blandit felis. Suspendisse mauris turpis, finibus id ultrices tempor, laoreet vel felis. Duis laoreet nisl mauris, id consequat felis elementum pretium. In pellentesque rutrum quam, sed tincidunt orci faucibus consectetur. Cras sagittis, felis non ultrices maximus, quam ligula pharetra lacus, non sollicitudin eros metus vitae sem. Sed pharetra urna lorem, nec dignissim nisl tempor id. Donec ullamcorper odio sapien. Nam pellentesque eleifend porttitor. Nam efficitur nunc et tristique finibus. Mauris ac consectetur leo, et tempus ante. Nam at porttitor ligula, ut dictum metus. Donec ullamcorper sapien quis sapien iaculis, vel luctus sapien sollicitudin. Etiam lobortis at risus in mollis.

                Aenean eget est ultrices, volutpat sem nec, imperdiet libero. In aliquet euismod convallis. Vivamus ligula urna, ultrices non pellentesque quis, aliquam vel est. Quisque lacinia libero id metus molestie pellentesque. Ut at cursus nulla. Donec sagittis ultricies turpis non dignissim. Nulla facilisi. Pellentesque vitae ante magna. Proin elit eros, cursus dignissim semper eget, interdum eget lacus. Nunc efficitur feugiat metus, eu pulvinar tortor accumsan at. Phasellus id luctus arcu. Vestibulum id molestie eros. Integer luctus, arcu a vulputate vehicula, ipsum mi ultricies ante, sed ultricies sapien ex nec nisl. Sed sit amet quam auctor, rhoncus diam sit amet, tempor turpis. Vivamus in faucibus dui.

                Aliquam erat volutpat. Suspendisse condimentum ullamcorper magna. Ut tincidunt efficitur euismod. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Duis mattis lobortis ex in semper. Integer porttitor eu lectus ac dapibus. Vivamus finibus, quam sit amet feugiat scelerisque, est leo semper mauris, nec rutrum est lorem ut turpis.
                </p>
                <p>
                Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut sem tortor, faucibus in pharetra in, malesuada in ante. Cras in ultricies mi, sed tempus enim. Duis vel dui luctus, maximus purus non, blandit felis. Suspendisse mauris turpis, finibus id ultrices tempor, laoreet vel felis. Duis laoreet nisl mauris, id consequat felis elementum pretium. In pellentesque rutrum quam, sed tincidunt orci faucibus consectetur. Cras sagittis, felis non ultrices maximus, quam ligula pharetra lacus, non sollicitudin eros metus vitae sem. Sed pharetra urna lorem, nec dignissim nisl tempor id. Donec ullamcorper odio sapien. Nam pellentesque eleifend porttitor. Nam efficitur nunc et tristique finibus. Mauris ac consectetur leo, et tempus ante. Nam at porttitor ligula, ut dictum metus. Donec ullamcorper sapien quis sapien iaculis, vel luctus sapien sollicitudin. Etiam lobortis at risus in mollis.

                Aenean eget est ultrices, volutpat sem nec, imperdiet libero. In aliquet euismod convallis. Vivamus ligula urna, ultrices non pellentesque quis, aliquam vel est. Quisque lacinia libero id metus molestie pellentesque. Ut at cursus nulla. Donec sagittis ultricies turpis non dignissim. Nulla facilisi. Pellentesque vitae ante magna. Proin elit eros, cursus dignissim semper eget, interdum eget lacus. Nunc efficitur feugiat metus, eu pulvinar tortor accumsan at. Phasellus id luctus arcu. Vestibulum id molestie eros. Integer luctus, arcu a vulputate vehicula, ipsum mi ultricies ante, sed ultricies sapien ex nec nisl. Sed sit amet quam auctor, rhoncus diam sit amet, tempor turpis. Vivamus in faucibus dui.

                Aliquam erat volutpat. Suspendisse condimentum ullamcorper magna. Ut tincidunt efficitur euismod. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Duis mattis lobortis ex in semper. Integer porttitor eu lectus ac dapibus. Vivamus finibus, quam sit amet feugiat scelerisque, est leo semper mauris, nec rutrum est lorem ut turpis.
                </p>
                <p>
                Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut sem tortor, faucibus in pharetra in, malesuada in ante. Cras in ultricies mi, sed tempus enim. Duis vel dui luctus, maximus purus non, blandit felis. Suspendisse mauris turpis, finibus id ultrices tempor, laoreet vel felis. Duis laoreet nisl mauris, id consequat felis elementum pretium. In pellentesque rutrum quam, sed tincidunt orci faucibus consectetur. Cras sagittis, felis non ultrices maximus, quam ligula pharetra lacus, non sollicitudin eros metus vitae sem. Sed pharetra urna lorem, nec dignissim nisl tempor id. Donec ullamcorper odio sapien. Nam pellentesque eleifend porttitor. Nam efficitur nunc et tristique finibus. Mauris ac consectetur leo, et tempus ante. Nam at porttitor ligula, ut dictum metus. Donec ullamcorper sapien quis sapien iaculis, vel luctus sapien sollicitudin. Etiam lobortis at risus in mollis.

                Aenean eget est ultrices, volutpat sem nec, imperdiet libero. In aliquet euismod convallis. Vivamus ligula urna, ultrices non pellentesque quis, aliquam vel est. Quisque lacinia libero id metus molestie pellentesque. Ut at cursus nulla. Donec sagittis ultricies turpis non dignissim. Nulla facilisi. Pellentesque vitae ante magna. Proin elit eros, cursus dignissim semper eget, interdum eget lacus. Nunc efficitur feugiat metus, eu pulvinar tortor accumsan at. Phasellus id luctus arcu. Vestibulum id molestie eros. Integer luctus, arcu a vulputate vehicula, ipsum mi ultricies ante, sed ultricies sapien ex nec nisl. Sed sit amet quam auctor, rhoncus diam sit amet, tempor turpis. Vivamus in faucibus dui.

                Aliquam erat volutpat. Suspendisse condimentum ullamcorper magna. Ut tincidunt efficitur euismod. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Duis mattis lobortis ex in semper. Integer porttitor eu lectus ac dapibus. Vivamus finibus, quam sit amet feugiat scelerisque, est leo semper mauris, nec rutrum est lorem ut turpis.
                </p>
                <p>
                Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut sem tortor, faucibus in pharetra in, malesuada in ante. Cras in ultricies mi, sed tempus enim. Duis vel dui luctus, maximus purus non, blandit felis. Suspendisse mauris turpis, finibus id ultrices tempor, laoreet vel felis. Duis laoreet nisl mauris, id consequat felis elementum pretium. In pellentesque rutrum quam, sed tincidunt orci faucibus consectetur. Cras sagittis, felis non ultrices maximus, quam ligula pharetra lacus, non sollicitudin eros metus vitae sem. Sed pharetra urna lorem, nec dignissim nisl tempor id. Donec ullamcorper odio sapien. Nam pellentesque eleifend porttitor. Nam efficitur nunc et tristique finibus. Mauris ac consectetur leo, et tempus ante. Nam at porttitor ligula, ut dictum metus. Donec ullamcorper sapien quis sapien iaculis, vel luctus sapien sollicitudin. Etiam lobortis at risus in mollis.

                Aenean eget est ultrices, volutpat sem nec, imperdiet libero. In aliquet euismod convallis. Vivamus ligula urna, ultrices non pellentesque quis, aliquam vel est. Quisque lacinia libero id metus molestie pellentesque. Ut at cursus nulla. Donec sagittis ultricies turpis non dignissim. Nulla facilisi. Pellentesque vitae ante magna. Proin elit eros, cursus dignissim semper eget, interdum eget lacus. Nunc efficitur feugiat metus, eu pulvinar tortor accumsan at. Phasellus id luctus arcu. Vestibulum id molestie eros. Integer luctus, arcu a vulputate vehicula, ipsum mi ultricies ante, sed ultricies sapien ex nec nisl. Sed sit amet quam auctor, rhoncus diam sit amet, tempor turpis. Vivamus in faucibus dui.

                Aliquam erat volutpat. Suspendisse condimentum ullamcorper magna. Ut tincidunt efficitur euismod. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Duis mattis lobortis ex in semper. Integer porttitor eu lectus ac dapibus. Vivamus finibus, quam sit amet feugiat scelerisque, est leo semper mauris, nec rutrum est lorem ut turpis.
                </p>
                <p>
                Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut sem tortor, faucibus in pharetra in, malesuada in ante. Cras in ultricies mi, sed tempus enim. Duis vel dui luctus, maximus purus non, blandit felis. Suspendisse mauris turpis, finibus id ultrices tempor, laoreet vel felis. Duis laoreet nisl mauris, id consequat felis elementum pretium. In pellentesque rutrum quam, sed tincidunt orci faucibus consectetur. Cras sagittis, felis non ultrices maximus, quam ligula pharetra lacus, non sollicitudin eros metus vitae sem. Sed pharetra urna lorem, nec dignissim nisl tempor id. Donec ullamcorper odio sapien. Nam pellentesque eleifend porttitor. Nam efficitur nunc et tristique finibus. Mauris ac consectetur leo, et tempus ante. Nam at porttitor ligula, ut dictum metus. Donec ullamcorper sapien quis sapien iaculis, vel luctus sapien sollicitudin. Etiam lobortis at risus in mollis.

                Aenean eget est ultrices, volutpat sem nec, imperdiet libero. In aliquet euismod convallis. Vivamus ligula urna, ultrices non pellentesque quis, aliquam vel est. Quisque lacinia libero id metus molestie pellentesque. Ut at cursus nulla. Donec sagittis ultricies turpis non dignissim. Nulla facilisi. Pellentesque vitae ante magna. Proin elit eros, cursus dignissim semper eget, interdum eget lacus. Nunc efficitur feugiat metus, eu pulvinar tortor accumsan at. Phasellus id luctus arcu. Vestibulum id molestie eros. Integer luctus, arcu a vulputate vehicula, ipsum mi ultricies ante, sed ultricies sapien ex nec nisl. Sed sit amet quam auctor, rhoncus diam sit amet, tempor turpis. Vivamus in faucibus dui.

                Aliquam erat volutpat. Suspendisse condimentum ullamcorper magna. Ut tincidunt efficitur euismod. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Duis mattis lobortis ex in semper. Integer porttitor eu lectus ac dapibus. Vivamus finibus, quam sit amet feugiat scelerisque, est leo semper mauris, nec rutrum est lorem ut turpis.
                </p>
                <p>
                Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut sem tortor, faucibus in pharetra in, malesuada in ante. Cras in ultricies mi, sed tempus enim. Duis vel dui luctus, maximus purus non, blandit felis. Suspendisse mauris turpis, finibus id ultrices tempor, laoreet vel felis. Duis laoreet nisl mauris, id consequat felis elementum pretium. In pellentesque rutrum quam, sed tincidunt orci faucibus consectetur. Cras sagittis, felis non ultrices maximus, quam ligula pharetra lacus, non sollicitudin eros metus vitae sem. Sed pharetra urna lorem, nec dignissim nisl tempor id. Donec ullamcorper odio sapien. Nam pellentesque eleifend porttitor. Nam efficitur nunc et tristique finibus. Mauris ac consectetur leo, et tempus ante. Nam at porttitor ligula, ut dictum metus. Donec ullamcorper sapien quis sapien iaculis, vel luctus sapien sollicitudin. Etiam lobortis at risus in mollis.

                Aenean eget est ultrices, volutpat sem nec, imperdiet libero. In aliquet euismod convallis. Vivamus ligula urna, ultrices non pellentesque quis, aliquam vel est. Quisque lacinia libero id metus molestie pellentesque. Ut at cursus nulla. Donec sagittis ultricies turpis non dignissim. Nulla facilisi. Pellentesque vitae ante magna. Proin elit eros, cursus dignissim semper eget, interdum eget lacus. Nunc efficitur feugiat metus, eu pulvinar tortor accumsan at. Phasellus id luctus arcu. Vestibulum id molestie eros. Integer luctus, arcu a vulputate vehicula, ipsum mi ultricies ante, sed ultricies sapien ex nec nisl. Sed sit amet quam auctor, rhoncus diam sit amet, tempor turpis. Vivamus in faucibus dui.

                Aliquam erat volutpat. Suspendisse condimentum ullamcorper magna. Ut tincidunt efficitur euismod. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Duis mattis lobortis ex in semper. Integer porttitor eu lectus ac dapibus. Vivamus finibus, quam sit amet feugiat scelerisque, est leo semper mauris, nec rutrum est lorem ut turpis.
                </p>
                <p>
                Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut sem tortor, faucibus in pharetra in, malesuada in ante. Cras in ultricies mi, sed tempus enim. Duis vel dui luctus, maximus purus non, blandit felis. Suspendisse mauris turpis, finibus id ultrices tempor, laoreet vel felis. Duis laoreet nisl mauris, id consequat felis elementum pretium. In pellentesque rutrum quam, sed tincidunt orci faucibus consectetur. Cras sagittis, felis non ultrices maximus, quam ligula pharetra lacus, non sollicitudin eros metus vitae sem. Sed pharetra urna lorem, nec dignissim nisl tempor id. Donec ullamcorper odio sapien. Nam pellentesque eleifend porttitor. Nam efficitur nunc et tristique finibus. Mauris ac consectetur leo, et tempus ante. Nam at porttitor ligula, ut dictum metus. Donec ullamcorper sapien quis sapien iaculis, vel luctus sapien sollicitudin. Etiam lobortis at risus in mollis.

                Aenean eget est ultrices, volutpat sem nec, imperdiet libero. In aliquet euismod convallis. Vivamus ligula urna, ultrices non pellentesque quis, aliquam vel est. Quisque lacinia libero id metus molestie pellentesque. Ut at cursus nulla. Donec sagittis ultricies turpis non dignissim. Nulla facilisi. Pellentesque vitae ante magna. Proin elit eros, cursus dignissim semper eget, interdum eget lacus. Nunc efficitur feugiat metus, eu pulvinar tortor accumsan at. Phasellus id luctus arcu. Vestibulum id molestie eros. Integer luctus, arcu a vulputate vehicula, ipsum mi ultricies ante, sed ultricies sapien ex nec nisl. Sed sit amet quam auctor, rhoncus diam sit amet, tempor turpis. Vivamus in faucibus dui.

                Aliquam erat volutpat. Suspendisse condimentum ullamcorper magna. Ut tincidunt efficitur euismod. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Duis mattis lobortis ex in semper. Integer porttitor eu lectus ac dapibus. Vivamus finibus, quam sit amet feugiat scelerisque, est leo semper mauris, nec rutrum est lorem ut turpis.
                </p>
                <p>
                Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut sem tortor, faucibus in pharetra in, malesuada in ante. Cras in ultricies mi, sed tempus enim. Duis vel dui luctus, maximus purus non, blandit felis. Suspendisse mauris turpis, finibus id ultrices tempor, laoreet vel felis. Duis laoreet nisl mauris, id consequat felis elementum pretium. In pellentesque rutrum quam, sed tincidunt orci faucibus consectetur. Cras sagittis, felis non ultrices maximus, quam ligula pharetra lacus, non sollicitudin eros metus vitae sem. Sed pharetra urna lorem, nec dignissim nisl tempor id. Donec ullamcorper odio sapien. Nam pellentesque eleifend porttitor. Nam efficitur nunc et tristique finibus. Mauris ac consectetur leo, et tempus ante. Nam at porttitor ligula, ut dictum metus. Donec ullamcorper sapien quis sapien iaculis, vel luctus sapien sollicitudin. Etiam lobortis at risus in mollis.

                Aenean eget est ultrices, volutpat sem nec, imperdiet libero. In aliquet euismod convallis. Vivamus ligula urna, ultrices non pellentesque quis, aliquam vel est. Quisque lacinia libero id metus molestie pellentesque. Ut at cursus nulla. Donec sagittis ultricies turpis non dignissim. Nulla facilisi. Pellentesque vitae ante magna. Proin elit eros, cursus dignissim semper eget, interdum eget lacus. Nunc efficitur feugiat metus, eu pulvinar tortor accumsan at. Phasellus id luctus arcu. Vestibulum id molestie eros. Integer luctus, arcu a vulputate vehicula, ipsum mi ultricies ante, sed ultricies sapien ex nec nisl. Sed sit amet quam auctor, rhoncus diam sit amet, tempor turpis. Vivamus in faucibus dui.

                Aliquam erat volutpat. Suspendisse condimentum ullamcorper magna. Ut tincidunt efficitur euismod. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Duis mattis lobortis ex in semper. Integer porttitor eu lectus ac dapibus. Vivamus finibus, quam sit amet feugiat scelerisque, est leo semper mauris, nec rutrum est lorem ut turpis.
                </p>
            </div>
        </div>
    )
}

export default Home;